<?php

namespace Domain\Customer\Services;

class OrganizationTestDataService
{
    public static function getOrgAPIData($taxNumber): ?array
    {
        $organizationData = [];

        $organizationData['10220278'] = [
            'taxpayerId' => '10220278',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'Profi Magyarország Zrt. "v.a."',
            'longName' => 'PROFI MAGYARORSZÁG KERESKEDELMI ZÁRTKÖRŰEN MŰKÖDŐ RÉSZVÉNYTÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1054',
                    'city' => 'BUDAPEST',
                    'streetName' => 'SZEMERE',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '17',
                    'floor' => 'IV',
                    'door' => '1',
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2310',
                    'city' => 'SZIGETSZENTMIKLÓS',
                    'streetName' => 'IFJUÚSÁG',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '16',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2730',
                    'city' => 'ALBERTIRSA',
                    'streetName' => 'SZABADSÁG',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '4',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10224612'] = [
            'taxpayerId' => '10224612',
            'vatCode' => '2',
            'countyCode' => '15',
            'shortName' => 'K SPED Kft. "f.a."',
            'longName' => 'K SPED FUVAROZÁSI ÉS SZÁLLÍTMÁNYOZÁSI KFT "FELSZÁMOLÁS ALATT"',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4400',
                    'city' => 'NYÍREGYHÁZA',
                    'streetName' => 'SZARVAS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1-3.',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10274019'] = [
            'taxpayerId' => '10274019',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'BUDACONSUM KFT.',
            'longName' => 'BUDACONSUM KERESKEDELMI ÉS SZOLGÁLTATO KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1025',
                    'city' => 'BUDAPEST',
                    'streetName' => 'CSATÁRKA',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '58.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2623',
                    'city' => 'KISMAROS',
                    'streetName' => 'SZOKOLYAI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '3',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2635',
                    'city' => 'VÁMOSMIKOLA',
                    'streetName' => 'KOSSUTH LAJOS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '4',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10307078'] = [
            'taxpayerId' => '10307078',
            'vatCode' => '2',
            'countyCode' => '44',
            'shortName' => 'TESCO-GLOBAL ZRT.',
            'longName' => 'TESCO-GLOBAL ÁRUHÁZAK ZÁRTKÖRŰEN MŰKÖDŐ RÉSZVÉNYTÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2040',
                    'city' => 'BUDAÖRS',
                    'streetName' => 'KINIZSI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '1-3',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2045',
                    'city' => 'TÖRÖKBÁLINT',
                    'streetName' => 'BAJCSY-ZSILINSZKY',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '67',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2462',
                    'city' => 'MARTONVÁSÁR',
                    'streetName' => 'ADY ENDRE',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '6.',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10352281'] = [
            'taxpayerId' => '10352281',
            'vatCode' => '2',
            'countyCode' => '43',
            'shortName' => 'TRIEX KFT',
            'longName' => 'TRIEX KERESKEDELMI KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1126',
                    'city' => 'BUDAPEST 12',
                    'streetName' => 'ZULEJKA U 6',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '7084',
                    'city' => 'PINCEHELY',
                    'streetName' => 'BELTERÜLET',
                    'publicPlaceCategory' => 'HRSZ',
                    'houseNumber' => '716/2.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2314',
                    'city' => 'HALÁSZTELEK',
                    'streetName' => 'BÉKE',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '5',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10485824'] = [
            'taxpayerId' => '10485824',
            'vatCode' => '2',
            'countyCode' => '07',
            'shortName' => 'SPAR MAGYARORSZÁG',
            'longName' => 'SPAR MAGYARORSZÁG KERESKEDELMI KORLÁTOLT FELELÖSSÉGÜ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2060',
                    'city' => 'BICSKE',
                    'streetName' => 'SPAR',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '326/1.HRSZ',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1117',
                    'city' => 'BUDAPEST',
                    'streetName' => 'DOMBÓVÁRI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '27',
                    'floor' => 'FSZT',
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '7451',
                    'city' => 'KAPOSVÁR',
                    'streetName' => 'ÁRPÁD',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '20',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10488559'] = [
            'taxpayerId' => '10488559',
            'vatCode' => '2',
            'countyCode' => '44',
            'shortName' => 'KRUPP ÉS TÁRSA KERESKEDELMI KFT',
            'longName' => 'KRUPP ÉS TÁRSA KERESKEDELMI KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2040',
                    'city' => 'BUDAÖRS',
                    'streetName' => 'SZABADSÁG ÚT 52-54',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2089',
                    'city' => 'TELKI',
                    'streetName' => 'NAPSUGÁR',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '2',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2440',
                    'city' => 'SZÁZHALOMBATTA',
                    'streetName' => 'DAMJANICH',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '23',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1122',
                    'city' => 'BUDAPEST',
                    'streetName' => 'KRISZTINA',
                    'publicPlaceCategory' => 'KÖRÚT',
                    'houseNumber' => '7',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10534485'] = [
            'taxpayerId' => '10534485',
            'vatCode' => '2',
            'countyCode' => '12',
            'shortName' => 'PALÓC NAGYKER KFT. "f. a."',
            'longName' => 'PALÓC NAGYKERESKEDELMI KORLÁTOLT FELELŐSSÉGÜ TÁRSASÁG "FELSZÁMOLÁS ALATT"',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '3104',
                    'city' => 'SALGÓTARJÁN',
                    'streetName' => 'IPARI PARK, PARK',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '9',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4800',
                    'city' => 'VÁSÁROSNAMÉNY',
                    'streetName' => 'JÓKAI',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '13',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4465',
                    'city' => 'RAKAMAZ',
                    'streetName' => 'ADY ENDRE',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1/A',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2230',
                    'city' => 'GYÖMRŐ',
                    'streetName' => 'BELTERÜLET',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => 'HRSZ 1006/1/B/10',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10539868'] = [
            'taxpayerId' => '10539868',
            'vatCode' => '2',
            'countyCode' => '44',
            'shortName' => 'KÜHNE + NAGEL KFT.',
            'longName' => 'KÜHNE + NAGEL SZÁLLÍTMÁNYOZÁSI KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2071',
                    'city' => 'PÁTY',
                    'streetName' => 'SZENT JÓZSEF',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '4',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '6000',
                    'city' => 'KECSKEMÉT',
                    'streetName' => 'BELTERÜLET',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '8683/403',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2220',
                    'city' => 'VECSÉS',
                    'streetName' => 'W1 BUDAPEST LISZT FERENC NEMZETKÖZI REPÜLŐTÉR, CARGO CITY',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8200',
                    'city' => 'VESZPRÉM',
                    'streetName' => 'PIRAMIS',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10627510'] = [
            'taxpayerId' => '10627510',
            'vatCode' => '2',
            'countyCode' => '07',
            'shortName' => 'PROCAR KFT',
            'longName' => 'PROCAR KERESKEDELMI ÉS ÜGYNÖKI KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8000',
                    'city' => 'SZÉKESFEHÉRVÁR',
                    'streetName' => 'KADOCSA U. 84',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10939622'] = [
            'taxpayerId' => '10939622',
            'vatCode' => '2',
            'countyCode' => '43',
            'shortName' => 'S.BEDI KFT',
            'longName' => 'S.BEDI KERESKEDELMI KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1117',
                    'city' => 'BUDAPEST',
                    'streetName' => 'FEHÉRVÁRI ÚTI VÁSÁRCSARNOK I/9-11, KŐRÖSY JÓZSEF',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '7-9',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2151',
                    'city' => 'FÓT',
                    'streetName' => 'MÓRICZ ZSIGMOND',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '23/A',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2141',
                    'city' => 'CSÖMÖR',
                    'streetName' => 'N/A',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '3521',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8083',
                    'city' => 'CSÁKVÁR',
                    'streetName' => 'N/A',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '772-773 HRSZ',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['10969629'] = [
            'taxpayerId' => '10969629',
            'vatCode' => '2',
            'countyCode' => '44',
            'shortName' => 'PENNY-MARKET KFT',
            'longName' => 'PENNY-MARKET KERESKEDELMI KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2351',
                    'city' => 'ALSÓNÉMEDI, ÉSZAKI-VÁLLALKOZÓI',
                    'streetName' => '5 FŐÚT',
                    'publicPlaceCategory' => '21',
                    'houseNumber' => 'KM',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4087',
                    'city' => 'HAJDÚDOROG',
                    'streetName' => 'BÖSZÖRMÉNYI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '29.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '3390',
                    'city' => 'FÜZESABONY',
                    'streetName' => 'ARANY JÁNOS',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '18',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1096',
                    'city' => 'BUDAPEST',
                    'streetName' => 'THALY KÁLMÁN',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '41',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['11243942'] = [
            'taxpayerId' => '11243942',
            'vatCode' => '2',
            'countyCode' => '15',
            'shortName' => 'Gávavencsellői Sütőüzem Kft "f. a."',
            'longName' => 'GÁVAVENCSELLŐI SÜTŐÜZEM KFT',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4472',
                    'city' => 'GÁVAVENCSELLŐ',
                    'streetName' => 'TOLDI',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '38',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4471',
                    'city' => 'GÁVAVENCSELLŐ',
                    'streetName' => 'SZABADSÁG',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '13',
                    'floor' => 'FSZT',
                    'door' => '3',
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '4471',
                    'city' => 'GÁVAVENCSELLŐ',
                    'streetName' => 'SZABADSÁG',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '13',
                    'floor' => '1',
                    'door' => '1',
                ],
            ],
        ];

        $organizationData['11816672'] = [
            'taxpayerId' => '11816672',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'CBA-Baldauf Kft.',
            'longName' => 'CBA-BALDAUF KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1028',
                    'city' => 'BUDAPEST',
                    'streetName' => 'HIDEGKUTI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '167',
                    'floor' => '1',
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2112',
                    'city' => 'VERESEGYHÁZ',
                    'streetName' => 'ERKEL FERENC',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2112',
                    'city' => 'VERESEGYHÁZ',
                    'streetName' => 'ERKEL FERENC',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '4',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1028',
                    'city' => 'BUDAPEST',
                    'streetName' => 'HIDEGKÚTI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '167',
                    'floor' => 'FSZT',
                    'door' => '1',
                ],
            ],
        ];

        $organizationData['11930035'] = [
            'taxpayerId' => '11930035',
            'vatCode' => '2',
            'countyCode' => '43',
            'shortName' => "CBA-REMIZ-KER '99 KFT.",
            'longName' => "CBA-REMIZ-KER '99 KERESKEDELMI KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG",
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1193',
                    'city' => 'BUDAPEST',
                    'streetName' => 'ÜLLŐI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '266',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1193',
                    'city' => 'BUDAPEST',
                    'streetName' => 'ÜLLŐI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '266',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['12392908'] = [
            'taxpayerId' => '12392908',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'CITY FOOD EURO Kft.',
            'longName' => 'CITY FOOD EURO KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1138',
                    'city' => 'BUDAPEST',
                    'streetName' => 'VÁCI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '175',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1066',
                    'city' => 'BUDAPEST',
                    'streetName' => 'TERÉZ',
                    'publicPlaceCategory' => 'KÖRÚT',
                    'houseNumber' => '54',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1111',
                    'city' => 'BUDAPEST',
                    'streetName' => 'KARINTHY FRIGYES',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '30-32',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1073',
                    'city' => 'BUDAPEST',
                    'streetName' => 'ERZSÉBET',
                    'publicPlaceCategory' => 'KÖRÚT',
                    'houseNumber' => '58',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['13066907'] = [
            'taxpayerId' => '13066907',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'NAGYMAROS TRADE KFT.',
            'longName' => 'NAGYMAROS TRADE KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1121',
                    'city' => 'BUDAPEST',
                    'streetName' => 'ÁRNYAS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '32-36',
                    'floor' => '1',
                    'door' => '1',
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2600',
                    'city' => 'VÁC',
                    'streetName' => 'ÁRPÁD',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '85.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1025',
                    'city' => 'BUDAPEST',
                    'streetName' => 'CSATÁRKA',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '58.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2600',
                    'city' => 'VÁC',
                    'streetName' => 'KÖLCSEY FERENC',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['13225265'] = [
            'taxpayerId' => '13225265',
            'vatCode' => '2',
            'countyCode' => '42',
            'shortName' => 'CBA-Újhegy Kft.',
            'longName' => 'CBA-ÚJHEGY INGATLANHASZNOSÍTÓ, KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1103',
                    'city' => 'BUDAPEST',
                    'streetName' => 'GYÖMRŐI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '99',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['13237912'] = [
            'taxpayerId' => '13237912',
            'vatCode' => '2',
            'countyCode' => '19',
            'shortName' => 'NAPCSILLAG KFT.',
            'longName' => 'NAPCSILLAG KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8400',
                    'city' => 'AJKA',
                    'streetName' => 'HÁRSFA',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '7500',
                    'city' => 'NAGYATÁD',
                    'streetName' => 'ÁRPÁD',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '71',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '3700',
                    'city' => 'KAZINCBARCIKA',
                    'streetName' => 'HADAK',
                    'publicPlaceCategory' => 'ÚTJA',
                    'houseNumber' => '11.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '9024',
                    'city' => 'GYŐR',
                    'streetName' => 'MALOMSZÉKI',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '9',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['13338037'] = [
            'taxpayerId' => '13338037',
            'vatCode' => '2',
            'countyCode' => '44',
            'shortName' => 'AUCHAN MAGYARORSZÁG Kft.',
            'longName' => 'AUCHAN MAGYARORSZÁG KFT.',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2040',
                    'city' => 'BUDAÖRS',
                    'streetName' => 'SPORT',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '2-4.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1103',
                    'city' => 'BUDAPEST',
                    'streetName' => 'GYÖMRŐI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '99',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2225',
                    'city' => 'ÜLLŐ',
                    'streetName' => 'ZSARÓKA',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '8',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8900',
                    'city' => 'ZALAEGERSZEG',
                    'streetName' => 'STADION',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '5.',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['13352479'] = [
            'taxpayerId' => '13352479',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'AMBROZIA FOOD KFT.',
            'longName' => 'AMBROZIA FOOD KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2051',
                    'city' => 'BIATORBÁGY',
                    'streetName' => 'KARIKÓ JÁNOS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '23',
                    'floor' => 'FSZT',
                    'door' => '4',
                ],
            ],
        ];

        $organizationData['13854641'] = [
            'taxpayerId' => '13854641',
            'vatCode' => '2',
            'countyCode' => '20',
            'shortName' => 'PAN-PRODUKT Kft. "f.a."',
            'longName' => 'PAN-PRODUKT KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG "FELSZÁMOLÁS ALATT"',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8360',
                    'city' => 'KESZTHELY',
                    'streetName' => 'KOSSUTH',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '35',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['14123472'] = [
            'taxpayerId' => '14123472',
            'vatCode' => '2',
            'countyCode' => '41',
            'shortName' => 'VÁROSHÁZ - CENTRÁL KFT.',
            'longName' => 'VÁROSHÁZ - CENTRÁL KERESKEDELMI KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1052',
                    'city' => 'BUDAPEST 05',
                    'streetName' => 'VÁROSHÁZ',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '14',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1082',
                    'city' => 'BUDAPEST',
                    'streetName' => 'FUTÓ',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '37-45',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['14371376'] = [
            'taxpayerId' => '14371376',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'Sarokház Cukrászat Kft. "v.a."',
            'longName' => 'SAROKHÁZ CUKRÁSZAT KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG "VÉGELSZÁMOLÁS ALATT"',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2132',
                    'city' => 'GÖD',
                    'streetName' => 'MÁRIA',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['14675302'] = [
            'taxpayerId' => '14675302',
            'vatCode' => '2',
            'countyCode' => '03',
            'shortName' => 'Nagyanyáink Sütödéje Kft.',
            'longName' => 'NAGYANYÁINK SÜTÖDÉJE KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '6000',
                    'city' => 'KECSKEMÉT',
                    'streetName' => 'RÁKÓCZI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '4.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '6000',
                    'city' => 'KECSKEMÉT',
                    'streetName' => 'SZABADSÁG',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '5',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2750',
                    'city' => 'NAGYKŐRÖS',
                    'streetName' => 'CEGLÉDI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '28.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '6200',
                    'city' => 'KISKŐRÖS',
                    'streetName' => 'KOSSUTH LAJOS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '61.',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['14772777'] = [
            'taxpayerId' => '14772777',
            'vatCode' => '2',
            'countyCode' => '11',
            'shortName' => 'MEDITRIO Kft.',
            'longName' => 'MEDITRIO KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2083',
                    'city' => 'SOLYMÁR',
                    'streetName' => 'KÜLSŐ VASÚT ÚT',
                    'publicPlaceCategory' => 'HOR IPARTEÜLET',
                    'houseNumber' => '.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '3530',
                    'city' => 'MISKOLC',
                    'streetName' => 'ERZSÉBET',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '4',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '9024',
                    'city' => 'GYŐR',
                    'streetName' => 'KÁLVÁRIA',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '21/B',
                    'floor' => 'FSZ',
                    'door' => '1',
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1052',
                    'city' => 'BUDAPEST',
                    'streetName' => 'HARIS',
                    'publicPlaceCategory' => 'KÖZ',
                    'houseNumber' => '6',
                    'floor' => 'MFSZT',
                    'door' => '1',
                ],
            ],
        ];

        $organizationData['14995679'] = [
            'taxpayerId' => '14995679',
            'vatCode' => '2',
            'countyCode' => '42',
            'shortName' => 'KRIKOL SPEDÍCIÓ Kft',
            'longName' => 'KRIKOL SPEDÍCIÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1152',
                    'city' => 'BUDAPEST',
                    'streetName' => 'VÉCSEY',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '58.',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['15329743'] = [
            'taxpayerId' => '15329743',
            'vatCode' => '2',
            'countyCode' => '43',
            'shortName' => 'BCE',
            'longName' => 'BUDAPESTI CORVINUS EGYETEM',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1093',
                    'city' => 'BUDAPEST',
                    'streetName' => 'FŐVÁM',
                    'publicPlaceCategory' => 'TÉR',
                    'houseNumber' => '8',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '8000',
                    'city' => 'SZÉKESFEHÉRVÁR',
                    'streetName' => 'BUDAI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '43',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1118',
                    'city' => 'BUDAPEST',
                    'streetName' => 'VILLÁNYI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '29-43',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1085',
                    'city' => 'BUDAPEST',
                    'streetName' => 'RIGÓ',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '3',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['18120141'] = [
            'taxpayerId' => '18120141',
            'vatCode' => '2',
            'countyCode' => '42',
            'shortName' => '',
            'longName' => 'MAGYAR ÉLELMISZERBANK EGYESÜLET',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1172',
                    'city' => 'BUDAPEST',
                    'streetName' => 'LOKÁTOR',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '3',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['18670457'] = [
            'taxpayerId' => '18670457',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'EÁ.ÁLLATMENHELY',
            'longName' => 'ELEK-ÁGH ÁLLATMENHELY ALAPÍTVÁNY',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2316',
                    'city' => 'TÖKÖL',
                    'streetName' => 'FŐ',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '129',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['19662927'] = [
            'taxpayerId' => '19662927',
            'vatCode' => '2',
            'countyCode' => '43',
            'shortName' => 'MÖSZ',
            'longName' => 'MAGYAR ÖKUMENIKUS SEGÉLYSZERVEZET',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1221',
                    'city' => 'BUDAPEST',
                    'streetName' => 'KOSSUTH L.',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '64',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['21798333'] = [
            'taxpayerId' => '21798333',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'BURGER SZIGET BT. "kt. a."',
            'longName' => 'BURGER SZIGET VENDÉGLÁTÓIPARI BETÉTI TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2314',
                    'city' => 'HALÁSZTELEK',
                    'streetName' => 'II. Rákóczi Ferenc',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '38',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2094',
                    'city' => 'NAGYKOVÁCSI',
                    'streetName' => '0106/17. HRSZ.',
                    'publicPlaceCategory' => 'N/A',
                    'houseNumber' => '',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1087',
                    'city' => 'BUDAPEST',
                    'streetName' => 'Kerepesi',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '29/B',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['22761356'] = [
            'taxpayerId' => '22761356',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'Mercurius Food Kft.',
            'longName' => 'MERCURIUS FOOD KERESKEDELMI ÉS SZOLGÁLTATÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2051',
                    'city' => 'BIATORBÁGY',
                    'streetName' => 'Karikó János',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '23',
                    'floor' => 'FSZT',
                    'door' => '4',
                ],
            ],
        ];

        $organizationData['22978112'] = [
            'taxpayerId' => '22978112',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'EUR-TRANZIT Kft',
            'longName' => 'EUR- TRANZIT KERESKEDELMI KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2040',
                    'city' => 'BUDAÖRS',
                    'streetName' => 'IBOLYA',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '77/E',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2051',
                    'city' => 'BIATORBÁGY',
                    'streetName' => 'ÁLLOMÁS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2040',
                    'city' => 'BUDAÖRS',
                    'streetName' => 'RAKTÁR',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1.',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2051',
                    'city' => 'BIATORBÁGY',
                    'streetName' => 'ÁLLOMÁS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '1',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['24071259'] = [
            'taxpayerId' => '24071259',
            'vatCode' => '2',
            'countyCode' => '03',
            'shortName' => 'DAO-PLUS Kft "f. a."',
            'longName' => 'DAO-PLUS KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '6221',
                    'city' => 'AKASZTÓ',
                    'streetName' => 'FŐ',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '62-64',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['24195382'] = [
            'taxpayerId' => '24195382',
            'vatCode' => '2',
            'countyCode' => '13',
            'shortName' => 'ARCTURUS 21 ALFA Kft. "v.a."',
            'longName' => 'ARCTURUS 21 ALFA KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG "VÉGELSZÁMOLÁS ALATT"',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '2051',
                    'city' => 'BIATORBÁGY',
                    'streetName' => 'KARIKÓ JÁNOS',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '23',
                    'floor' => 'FSZT',
                    'door' => '4',
                ],
            ],
        ];

        $organizationData['25072394'] = [
            'taxpayerId' => '25072394',
            'vatCode' => '2',
            'countyCode' => '42',
            'shortName' => 'CBA-Grand Gourmet Kft.',
            'longName' => 'CBA-GRAND GOURMET KERESKEDELMI ÉS VENDÉGLÁTÓ KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1103',
                    'city' => 'BUDAPEST',
                    'streetName' => 'GYÖMRŐI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '99',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '1036',
                    'city' => 'BUDAPEST',
                    'streetName' => 'BÉCSI',
                    'publicPlaceCategory' => 'ÚT',
                    'houseNumber' => '38-44',
                    'floor' => null,
                    'door' => null,
                ],
            ],
        ];

        $organizationData['25577710'] = [
            'taxpayerId' => '25577710',
            'vatCode' => '2',
            'countyCode' => '08',
            'shortName' => 'GYŐRI ÉDENKERT Kft.',
            'longName' => 'GYŐRI ÉDENKERT KORLÁTOLT FELELŐSSÉGŰ TÁRSASÁG',
            'addresses' => [
                [
                    'countryCode' => 'HU',
                    'postalCode' => '9026',
                    'city' => 'GYŐR',
                    'streetName' => 'SELMECI',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '10',
                    'floor' => null,
                    'door' => null,
                ],
                [
                    'countryCode' => 'HU',
                    'postalCode' => '9021',
                    'city' => 'GYŐR',
                    'streetName' => 'KIRÁLY',
                    'publicPlaceCategory' => 'UTCA',
                    'houseNumber' => '15',
                    'floor' => 'FSZT',
                    'door' => '4',
                ],
            ],
        ];

        return isset($organizationData[$taxNumber]) ? $organizationData[$taxNumber] : null;
    }
}
